#!/bin/bash

# Be sure and set the .yarnrc file in this directory to
# match the ROOT variable below...

ROOT=/tmp14

cp .yarnrc $ROOT/mui-tutorial-demo/ghw-autosuggest/v1

cp .yarnrc $ROOT/mui-tutorial-demo/ghw-drawer/v1

cp .yarnrc $ROOT/mui-tutorial-demo/ghw-menu/v1

cp .yarnrc $ROOT/mui-tutorial-demo/mui-doc/v1

cp .yarnrc $ROOT/mui-tutorial-demo/mui-drawer/v1

cp .yarnrc $ROOT/mui-tutorial-demo/mui-md/v1

cp .yarnrc $ROOT/mui-tutorial-demo/mui-menu/v1
